편지만드는ing
GSM-MSG/MSG-Front pull request #5
Opened 2022-05-27 12:53 UTC by jjaejjae12

편지만드는ing

2022-05-27 12:54 UTC, kimsh153 approved these changes

2022-05-27 12:56 UTC, pasin7793 approved these changes

2022-05-27 12:56 UTC, baekteun commented on src/pages/afterschool/index.tsx
> +    title?: string,
얘 왜 옵셔널임

2022-05-27 12:56 UTC, baekteun commented on src/pages/afterschool/index.tsx
> +    isApplied: 0 | 1
bool 안씀?

2022-05-27 13:24 UTC, baekteun approved these changes

2022-05-27 13:25 UTC, louis7308 approved these changes

2022-05-27 13:37 UTC, yoonjibin approved these changes

2022-05-27 13:40 UTC, chanwoo00106 commented
pr 날릴 때 화면 캡쳐해 주면 좋을 것 같아

2022-05-27 14:42 UTC, khs3994 approved these changes

2022-05-28 03:21 UTC, Huuuunee approved these changes

2022-05-28 07:46 UTC, chanwoo00106 requested changes

2022-05-28 07:46 UTC, chanwoo00106 commented on src/pages/afterschool/index.tsx
> +const AfterMoveBox = styled.div`
이거는 style.ts 파일에 넣어주고

2022-05-28 07:46 UTC, chanwoo00106 commented on src/pages/afterschool/index.tsx
> +    position: fixed;
이것도 style.ts 파일에 넣어주고

2022-05-28 07:46 UTC, chanwoo00106 commented on src/pages/afterschool/index.tsx
> +type ListType = {
이런 타입들은 types 폴더에 넣어서 관리해줘

2022-05-28 07:46 UTC, chanwoo00106 commented on src/pages/afterschool/index.tsx
> +    ])
이것들도 dummy data로 따로 보관해줘

2022-05-28 07:46 UTC, chanwoo00106 commented on src/pages/afterschool/index.tsx
> +    ];
이런 거는 dummy data로 따로 보관해줘

2022-05-28 07:46 UTC, chanwoo00106 commented on src/pages/afterschool/style.ts
> +    /* animation: 3s ease-in 1s 2 reverse both paused slidein;  */
이 주석들 뭐야

2022-05-28 07:46 UTC, chanwoo00106 commented on src/SVG/letter.tsx
> +        <svg width="225" height="174" viewBox="0 0 225 174" fill="none" xmlns="http://www.w3.org/2000/svg">
이거 svg 파일이 너무 큼
svgomg 라는 사이트에서 크기를 상당히 많이 줄일 수 있으니깐 참고해

2022-05-28 07:46 UTC, chanwoo00106 commented on src/pages/afterschool/index.tsx
> +    isApplied: 0 | 1
이거 boolean으로 바꾸는 게 좋을 것 같음
만약 백에서 진짜로 저렇게 오면 백이 boolean으로 바꿔야 하고

2022-05-28 07:52 UTC, jjaejjae12 commented on src/pages/afterschool/index.tsx
> +    isApplied: 0 | 1
boolean으로 바꿈

2022-05-28 07:53 UTC, jjaejjae12 commented on src/pages/afterschool/style.ts
> +    /* animation: 3s ease-in 1s 2 reverse both paused slidein;  */
지우는중

2022-05-31 15:13 UTC, closed without merging