After school
GSM-MSG/MSG-Front pull request #6
Opened 2022-06-14 07:00 UTC by jjaejjae12

* 방과후 어드민 전체 방과후 리스트 보여주는 페이지 제작
* 방과후 수정 모달 제작
* 방과후 개설 모달 제작
* 방과후 전체 명단 보기 페이지 제작
* 방과후 명단보기 페이지 인원 조회 모달  제작
* 방과후 전체 오픈&전체 마감 시즌 선택 모달 제작
* 디테일 페이지 제작
* 동아리 어드민페이지 첫 화면 제작
* 어드민 MSG첫 화면 제작

2022-06-14 07:03 UTC, baekteun commented on src/components/StuSearch/DummyData.ts
> +type DD = {
?????????????????????????????????

2022-06-14 07:03 UTC, baekteun commented on src/pages/adminpeople/DummyData.ts
> +    class: 2,
더미 빼래

2022-06-14 07:05 UTC, louis7308 approved these changes

2022-06-14 07:05 UTC, khs3994 approved these changes

2022-06-14 07:07 UTC, jjaejjae12 commented on src/pages/adminpeople/DummyData.ts
> +    class: 2,
더미파일 그냥 지워?

2022-06-14 07:08 UTC, baekteun commented on src/pages/adminpeople/DummyData.ts
> +    class: 2,
아니아니 일단 냅두라고.. 할까?

2022-06-14 07:08 UTC, baekteun commented on src/pages/adminpeople/DummyData.ts
> +    class: 2,
아니아니 일단 냅두라고.. 할까?

2022-06-14 07:08 UTC, baekteun commented on src/pages/adminpeople/DummyData.ts
> +    class: 2,
래

2022-06-14 07:35 UTC, Huuuunee approved these changes

2022-06-15 00:49 UTC, kimsh153 approved these changes

2022-06-15 04:49 UTC, yoonjibin approved these changes

2022-06-15 04:55 UTC, sagwamatrlawns approved these changes

2022-06-15 07:04 UTC, chanwoo00106 requested changes

2022-06-15 07:04 UTC, chanwoo00106 commented on next.config.js
> -  reactStrictMode: true,
이런 config 파일은 앞으로 상의 하고 변경하자

2022-06-15 07:04 UTC, chanwoo00106 commented on next.config.js
> -  reactStrictMode: true,
글고 이거 true로 바꾸셈

2022-06-15 07:04 UTC, chanwoo00106 commented on src/SVG/SearchIcon.tsx
> +import { cp } from "fs";
이건 import 왜 한 거임?

2022-06-15 07:04 UTC, chanwoo00106 commented on src/SVG/index.ts
> +
왜 자꾸 이상한 걸 import 할까

2022-06-15 07:04 UTC, chanwoo00106 commented on src/components/AdminFix/index.tsx
> +  const ChangeGrade = (e: any) => {
any 타입은 최대한 지양해줘

2022-06-15 07:04 UTC, chanwoo00106 commented on src/components/StuSearch/index.tsx
> +export function StuSearch({ fn }: any) {
`fn`은 좀 아닌 것 같고 any 타입도 바꿔주고

2022-06-15 07:04 UTC, chanwoo00106 commented on src/components/StuSearch/index.tsx
> +import { type } from "os";
진짜 왜...

2022-06-15 07:04 UTC, chanwoo00106 commented on src/pages/adminpeople/index.tsx
> +  //몰라
이 주석은 뭘까요?

2022-06-15 07:04 UTC, chanwoo00106 commented on src/types/AfterSchoolType.ts
> +import { type } from "os";
진짜 뭐야

2022-06-15 07:04 UTC, chanwoo00106 commented on src/components/CreateAfterSchool/index.tsx
> +import { text } from "stream/consumers";
이거는 뭐 하는 거임?

2022-06-15 07:04 UTC, chanwoo00106 commented on src/components/AdminFix/index.tsx
> +  const ChangeDay = (e: any) => {
아으 진짜

2022-06-15 07:06 UTC, jjaejjae12 commented on next.config.js
> -  reactStrictMode: true,
다시 바꿈

2022-06-15 07:06 UTC, chanwoo00106 commented on src/components/StuSearch/DummyData.ts
> +type DD = {
그래도 DD는 아니지

2022-06-15 07:06 UTC, chanwoo00106 commented on src/pages/adminpeople/DummyData.ts
> +    class: 2,
진짜 any 그만 써

2022-06-15 07:08 UTC, jjaejjae12 commented on src/SVG/SearchIcon.tsx
> +import { cp } from "fs";
지움

2022-06-15 07:08 UTC, jjaejjae12 commented on src/SVG/index.ts
> +
지웠어

2022-06-15 07:20 UTC, chanwoo00106 commented on next.config.js
> -  reactStrictMode: true,
push 하고 resolve 해줘
또 한꺼번에 올리지 말고

2022-06-15 07:51 UTC, jjaejjae12 commented on src/components/StuSearch/index.tsx
> +import { type } from "os";
지움

2022-06-15 07:56 UTC, jjaejjae12 commented on src/pages/adminpeople/index.tsx
> +  //몰라
경민이꺼 코드 가지고 온건데 detail페이지에서 필요한거라고 해서 남겨놨는데 일단 지움

2022-06-15 07:58 UTC, jjaejjae12 commented on src/components/StuSearch/index.tsx
> +import { type } from "os";
지웠어

2022-06-15 07:59 UTC, jjaejjae12 commented on src/types/AfterSchoolType.ts
> +import { type } from "os";
지웠어

2022-06-15 08:00 UTC, chanwoo00106 commented on src/pages/adminpeople/index.tsx
> +  //몰라
일단 이 pr에서는 필요 없는 거잖아

2022-06-15 08:27 UTC, louis7308 commented on src/components/AdminFix/index.tsx
> +  const ChangeDay = (e: any) => {
[주소](https://github.com/GSM-MSG/MSG-Front/pull/6)

2022-06-15 10:13 UTC, jjaejjae12 commented on src/components/StuSearch/DummyData.ts
> +type DD = {
이름 바꿨어 [DD변수명수정](https://github.com/GSM-MSG/MSG-Front/pull/6/commits/0f6730daf789ae4d726a6bfec4349959489b7336)

2022-06-15 10:14 UTC, jjaejjae12 commented on src/components/StuSearch/index.tsx
> +export function StuSearch({ fn }: any) {
[fn수정](https://github.com/GSM-MSG/MSG-Front/pull/6/commits/0f6730daf789ae4d726a6bfec4349959489b7336)

2022-06-15 10:15 UTC, jjaejjae12 commented on src/components/CreateAfterSchool/index.tsx
> +import { text } from "stream/consumers";
[필요없는import삭제](https://github.com/GSM-MSG/MSG-Front/pull/6/commits/0f6730daf789ae4d726a6bfec4349959489b7336)

2022-06-15 11:25 UTC, chanwoo00106 commented
음... 영재야 큰일 났는데
![image](https://user-images.githubusercontent.com/57276315/173815962-3625f7e4-9454-4f8e-9835-a63202c7ee1b.png)
지금 파일 구조가 이렇게 되어있는데 pages 아래에는 page에 보여야 할 부분만 올리는 부분이야 그러다 보니깐 components에 있어야 할 것들이 여기에 있으면 안된다는 뜻이지
이건 내가 nextjs에 대해서 잘 안 알려준 내 문제도 있긴 하지 어쨌든 파일 구조를 많이 변경해야 할 것 같아

2022-06-16 00:40 UTC, jjaejjae12 commented on src/pages/adminpeople/DummyData.ts
> +    class: 2,
[any 수정](https://github.com/GSM-MSG/MSG-Front/pull/6/commits/1c7660c9e31273cf896df50a9c2a5345ae536322)

2022-06-16 00:40 UTC, jjaejjae12 commented on src/components/AdminFix/index.tsx
> +  const ChangeGrade = (e: any) => {
[타입수정](https://github.com/GSM-MSG/MSG-Front/pull/6/commits/1c7660c9e31273cf896df50a9c2a5345ae536322)

2022-06-16 00:41 UTC, jjaejjae12 commented on src/components/StuSearch/index.tsx
> +export function StuSearch({ fn }: any) {
[타입수정](https://github.com/GSM-MSG/MSG-Front/pull/6/commits/1c7660c9e31273cf896df50a9c2a5345ae536322)

2022-06-16 00:41 UTC, jjaejjae12 commented on src/components/AdminFix/index.tsx
> +  const ChangeDay = (e: any) => {
[타입수정](https://github.com/GSM-MSG/MSG-Front/pull/6/commits/1c7660c9e31273cf896df50a9c2a5345ae536322)

2022-06-22 13:42 UTC, closed without merging